services:

  evolution-api:
    image: evoapicloud/evolution-api:latest
    container_name: evolution-api
    restart: always

    ports:
      - "8080:8080"

    env_file:
      - .env

    depends_on:
      - postgres
      - redis


  postgres:
    image: postgres:15
    container_name: evolution-postgres
    restart: always

    environment:
      POSTGRES_DB: evolution
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: evolution123

    volumes:
      - postgres_data:/var/lib/postgresql/data


  redis:
    image: redis:latest
    container_name: evolution-redis
    restart: always

    volumes:
      - redis_data:/data


volumes:
  postgres_data:
  redis_data: